### PR TITLE
FIX: remove plus minus react as Saint Luke handles it better now

### PR DESCRIPTION
**Pull request by HrachAsatryan**
Since Saint Luke now also reacts + and - (and has logic to remove a react when a second person reacts) Hrachinator reacting is redundant and works against those changes

### CODE REVIEW

**Comment by karapnaran** [comment]
Hrachinator reacting +- is an integral part of it's personality and it was made this way to mimic the person it was based on. On the other hand Saint Luke reacting doesn't really make sense to me, and I don't think it should be a part of his responsibilities.

If you believe that the reactions are too intrusive and negatively impact your server experience, we can add something similar to the reaction removal mechanism that Luke has, but I don't think that's necessary (or a good change). Closing the pull request, please reopen it if you still believe it's needed.

**Comment by gavjan** [comment]
What if Saint Luke removes Hrachinator's reactions when necessary? However, in case someone reacts and then removes their reaction, Saint Luke won't be able to add back Hrachinator's reaction, and will have no choice but to react on his own behalf.

**Comment by rcgRaf** [comment]
@karapnaran we don't need to count bots when calling out @Dota @Deadlock or e.t.c it's easier to see the exact number of people ready to play

**Comment by rcgRaf** [comment]
Initial reactions are meant to show the "buttons" when someone reacts we don't need the bots react anymore

**Comment by karapnaran** [comment]
meh, whatever

**Pull request merged**
